Repository react-storefront-community/react-storefront, pull requests merged in 2020-02, with the labels that each got.

#36 Fix doc generation to correctly push latest docs when published to npm
  .github/workflows/publish.yml
  .storybook/createMetadata.js
  docs/buildDocs.js
  docs/moduleParser.js
  package.json
  src/BackToTop.js
  src/Breadcrumbs.js
  src/CartButton.js
  src/Offline.js
  src/Rating.js
  src/carousel/CarouselArrows.js
  src/carousel/CarouselThumbnails.js
  src/carousel/MediaCarousel.js
  src/link/Link.js
  src/menu/Menu.js
  src/menu/MenuBody.js
  src/menu/MenuBranch.js
  src/menu/MenuButton.js
  src/menu/MenuItem.js
  src/nav/NavTab.js
  src/option/ProductOption.js
  src/option/ProductOptionSelector.js
  src/option/SwatchProductOption.js
  src/option/TextProductOption.js
  src/plp/ButtonFilterGroup.js
  src/plp/CheckboxFilterGroup.js
  src/plp/FacetGroup.js
  src/plp/Filter.js
  src/plp/FilterButton.js
  src/plp/FilterFooter.js
  src/plp/FilterHeader.js
  src/plp/SearchResultsProvider.js
  src/plp/ShowMore.js
  src/plp/Sort.js
  src/plp/SortButton.js
  src/plp/useSearchResultsStore.js
  src/search/SearchButton.js
  src/search/SearchDrawer.js
  src/search/SearchField.js
  src/search/SearchForm.js
  src/search/SearchHeader.js
  src/search/SearchProvider.js
  src/search/SearchSubmitButton.js
  src/search/SearchSuggestionGroup.js
  src/search/SearchSuggestionItem.js
  src/search/SearchSuggestions.js
Labels: chore

#43 Cleanup for docs and invalid prop types
  .github/release-draft-template.yml
  src/Breadcrumbs.js
  src/carousel/Media.js
  src/carousel/MediaCarousel.js
  src/fetch.js
Labels: documentation

#29 Added storybook stories
  .storybook/main.js
  .storybook/stories/Accordion.stories.js
  .storybook/stories/ActionButton.stories.js
  .storybook/stories/AutoScrollToNewChildren.stories.js
  .storybook/stories/BackToTop.stories.js
  .storybook/stories/Breadcrumbs.stories.js
  .storybook/stories/Carousel.stories.js
  .storybook/stories/CartButton.stories.js
  .storybook/stories/CheckboxFilterGroup.stories.js
  .storybook/stories/ExpandableSection.stories.js
  .storybook/stories/Image.stories.js
  .storybook/stories/Lazy.stories.js
  .storybook/stories/MediaCarousel.stories.js
  .storybook/stories/NavTabs.stories.js
  .storybook/stories/Offline.stories.js
  .storybook/stories/ProductOptionSelector.stories.js
  .storybook/stories/QuantitySelector.stories.js
  .storybook/stories/Rating.stories.js
  .storybook/stories/ToolbarButton.stories.js
  package-lock.json
  package.json
  src/carousel/Carousel.js
  src/carousel/MediaCarousel.js
Labels: chore

#44 Improve test coverage
  package.json
  src/carousel/MagnifyHint.js
  src/carousel/MediaCarousel.js
  src/drawer/Drawer.js
  src/drawer/DrawerCloseButton.js
  src/drawer/DrawerContext.js
  src/menu/MenuLeaf.js
  src/nav/NavTab.js
  src/plp/SortButton.js
  src/props/createLazyProps.js
  src/props/fulfillAPIRequest.js
  test/ReponsiveTiles.test.js
  test/carousel/Carousel.test.js
  test/carousel/CarouselArrows.test.js
  test/carousel/CarouselDots.test.js
  test/carousel/CarouselThumbnails.test.js
  test/carousel/Lightbox.test.js
  test/carousel/MagnifyHint.test.js
  test/carousel/Media.test.js
  test/carousel/MediaCarousel.test.js
  test/config/mocks.js
  test/drawer/Drawer.test.js
  test/drawer/DrawerCloseButton.test.js
  test/hooks/useAppStore.test.js
  test/hooks/useTraceUpdate.test.js
  test/link/Link.test.js
  test/menu/Menu.test.js
  test/menu/MenuItem.test.js
  test/middlewares/withAmpFormParser.test.js
  test/mocks/mockObservers.js
  test/nav/NavTab.test.js
  test/plp/SortButton.test.js
  test/props/createLazyProps.test.js
  test/props/fulfillAPIRequest.test.js
  test/router/storeInitialPropsInHistory.test.js
  test/server/getRoutes.test.js
  test/session/SessionProvider.test.js
  test/utils/isBrowser.test.js
  test/utils/lazyLoadImages.test.js
  test/utils/withCaching.test.js
Labels: chore

#48 Update storybook metadata creation to support Knobs in docs app
  .github/workflows/publish.yml
  .storybook/createMetadata.js
  .storybook/stories/ActionButton.stories.js
  .storybook/stories/Drawer.stories.js
  .storybook/stories/LoadMask.stories.js
  .storybook/stories/ResponsiveTiles.stories.js
  .storybook/stories/TabPanel.stories.js
  package.json
  src/AppBar.js
  src/ForwardThumbnail.js
  src/TabPanel.js
Labels: documentation

#45 Pause prefetches when non-prefetch request is sent to origin
  package-lock.json
  package.json
  service-worker/bootstrap.js
  test/bootstrap.test.js
  test/config/babelTransformer.js
  test/config/setup.js
Labels: enhancement
