Repository react-storefront-community/react-storefront, pull requests merged in 2020-03, with the labels that each got.

#57 Add test coverage for service worker
  service-worker/bootstrap.js
  test/bootstrap.test.js
Labels: chore

#50 Hide MagnifyHint when image is already fully magnified, and use magnified image in Lightbox
  src/carousel/Carousel.js
  src/carousel/MediaCarousel.js
  test/carousel/MediaCarousel.test.js
Labels: bug

#59 Removed the console message about preact.
  plugins/withReactStorefront.js
Labels: chore

#58 Modular workbox
  babel.config.js
  jest.config.js
  package.json
  plugins/withReactStorefront.js
  plugins/withServiceWorker.js
  service-worker/copyBootstrap.js
  service-worker/service-worker.js
  test/service-worker.test.js
Labels: chore

#53 Desktop search
  src/search/SearchDrawer.js
  src/search/SearchField.js
  src/search/SearchForm.js
  src/search/SearchPopover.js
  src/search/SearchProvider.js
  src/search/SearchSuggestions.js
  test/hooks/useNavigationEvent.test.js
  test/search/SearchDrawer.test.js
  test/search/SearchField.test.js
  test/search/SearchForm.test.js
  test/search/SearchPopover.test.js
  test/search/SearchProvider.test.js
  test/search/SearchSuggetions.test.js
Labels: enhancement

#64 MediaCarousel functionality improvements
  package.json
  src/carousel/Carousel.js
  src/carousel/CarouselThumbnails.js
  src/carousel/Media.js
  src/carousel/MediaCarousel.js
  test/carousel/CarouselThumbnails.test.js
  test/carousel/MediaCarousel.test.js
Labels: enhancement, in progress
