Repository react-storefront-community/react-storefront, pull requests merged in 2020-01, with the labels that each got.

#20 fix: Service worker category navigation content updating and add subc…
  package-lock.json
  package.json
  src/PWA.js
  src/hooks/useLazyStore.js
  src/link/Link.js
  src/nav/NavTab.js
  src/props/fetchProps.js
Labels: bug

#19 Added doc generator; push updated doc when package is published
  .github/release-draft-template.yml
  .github/release-drafter.yml
  .github/workflows/publish.yml
  .github/workflows/release-drafter.yml
  .gitignore
  docs/buildDocs.js
  docs/moduleParser.js
  package-lock.json
  package.json
  src/Accordion.js
  src/ActionButton.js
  src/AppBar.js
  src/AutoScrollToNewChildren.js
  src/BackToTop.js
  src/Box.js
  src/Breadcrumbs.js
  src/CartButton.js
  src/CmsSlot.js
  src/ExpandableSection.js
  src/Fill.js
  src/Image.js
  src/Label.js
  src/Lazy.js
  src/LoadMask.js
  src/Offline.js
  src/QuantitySelector.js
  src/Rating.js
  src/ResponsiveTiles.js
  src/Row.js
  src/Spacer.js
  src/TabPanel.js
  src/ToolbarButton.js
  src/carousel/Carousel.js
  src/carousel/CarouselArrows.js
  src/carousel/CarouselDots.js
  src/carousel/CarouselThumbnails.js
  src/carousel/Lightbox.js
  src/carousel/MagnifyHint.js
  src/carousel/Media.js
  src/carousel/MediaCarousel.js
  src/drawer/Drawer.js
  src/drawer/DrawerCloseButton.js
  src/hooks/useAppStore.js
  src/hooks/useStateFromProp.js
  src/link/Link.js
  src/nav/NavTab.js
  src/nav/NavTabs.js
  src/plp/Filter.js
  src/plp/FilterButton.js
  src/plp/SortButton.js
  src/props/fetchProps.js
  src/props/fulfillAPIRequest.js
  src/router/replaceState.js
  src/router/storeInitialPropsInHistory.js
  src/search/SearchSuggestions.js
  src/utils/lazyLoadImages.js
  src/utils/merge.js
Labels: chore

#26 Add `createTheme` to prevent users from overwriting core theme variables
  src/theme/createTheme.js
  test/theme/createTheme.test.js
Labels: enhancement
